version: '3.4'

# TODO replace postgres/setup.sql with a bash script that does the same and doesn't have any passwords stored on it
services:
  flowable-db:
    image: postgres:14
    environment:
      POSTGRES_DB: flowable
      POSTGRES_USER: flowable
      POSTGRES_PASSWORD: flowable
    ports:
      - "5432:5432"
    volumes:
      - ../../resources/sql/create-database:/docker-entrypoint-initdb.d
      - data_db:/var/lib/postgresql/data

  flowable-index:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      discovery.type: single-node
      node.name: flowable-node-01
      cluster.name: flowable-cluster
      xpack.security.enabled: "false"
    ports:
      - "9300:9300"
      - "9200:9200"
    volumes:
      - data_index:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1

  mailhog:
    image: mailhog/mailhog
    ports:
      - "25:1025"
      - "8025:8025"

# Volumes will get a prefix based on the `.env` file and data can be cleared by `docker-compose down -v`
volumes:
  data_db:
  data_index:
