apiVersion: v1
kind: Secret
metadata:
  name: pgadmin4-servers
type: Opaque
stringData:
  pgadmin4-servers: |
    {
      "Servers": {
        "1": {
          "Name": "Flowable",
          "Group": "Servers",
          "Host": "onetrade-tests-postgres",
          "Port": 5432,
          "MaintenanceDB": "postgres",
          "Username": "onetrade",
          "PassFile": "/var/lib/pgadmin/storage/admin.pagonxt_onetradefinance.pagonxt.com/file.pgpass",
          "SSLMode": "prefer"
        }
      }
    }
